# Generated by Django 3.1.1 on 2020-09-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('notícias', 'Notícias'), ('tecnológia', 'Tecnológia'), ('cultura', 'Cultura'), ('tirinhas', 'Tirinhas'), ('motivação', 'Motivação'), ('ciência', 'Ciência'), ('saúde', 'Saúde'), ('estilo', 'Estilo'), ('viajem', 'Viajem')], default='notícias', max_length=11),
        ),
    ]
