# Generated by Django 3.1 on 2020-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200922_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('notícias', 'Notícias'), ('tecnológia', 'Tecnológia'), ('cultura', 'Cultura'), ('tirinhas', 'Tirinhas'), ('motivação', 'Motivação'), ('ciência', 'Ciência'), ('saúde', 'Saúde'), ('viajem', 'Viajem')], default='notícias', max_length=11),
        ),
    ]
